- name: First Play. Using serial strategy.
  hosts: all
  gather_facts: yes
  serial: 1
  tasks:
    - name: Play1 Debug1 task
      debug:
        msg: "This is Play1 debug1 task"

    - name: Play1 Debug2 task
      debug:
        msg: "This is Play1 debug2 task"
